-- Thêm cột phone vào bảng users
ALTER TABLE public.users ADD COLUMN phone VARCHAR(20);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar VARCHAR(255);
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS is_api BOOLEAN DEFAULT FALSE;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1;
ALTER TABLE public.news_international ADD COLUMN IF NOT EXISTS is_api BOOLEAN DEFAULT FALSE;
ALTER TABLE public.saved_news ADD COLUMN IF NOT EXISTS site VARCHAR(10) DEFAULT 'vn';
ALTER TABLE public.viewed_news ADD COLUMN IF NOT EXISTS site VARCHAR(10) DEFAULT 'vn';
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS site VARCHAR(10) DEFAULT 'vn';
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE public.news_international ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS tags_string TEXT;
ALTER TABLE public.news_international ADD COLUMN IF NOT EXISTS tags_string TEXT;
ALTER TABLE news ADD COLUMN author VARCHAR(255) DEFAULT NULL;